services:
  postgres:
    image: postgres:17
    container_name: pg-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-!!!SET POSTGRES_USER!!!}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!!!SET POSTGRES_PASSWORD!!!}
      POSTGRES_DB: ${POSTGRES_DB:-!!!SET POSTGRES_DB!!!}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: >
      postgres -c config_file=/etc/postgresql/postgresql.conf
    shm_size: 2g
    mem_limit: 5g
